version: '3.7'
services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./packages/backend/Dockerfile
  #   restart: always
  #   ports:
  #     - 3333:3333
  postgres:
    image: postgres:10.3
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'
volumes:
  postgres: {}
